services:
  # Minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9001:9001" #local:cnt
      - "9000:9000"
    volumes:
      - ./docker/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin1234
      - MINIO_ROOT_PASSWORD=admin1234
      - MINIO_DEFAULT_BUCKETS=snapshot
    command: ["server", "/data", "--console-address", ":9001"] 
    networks:
      - default
  
  #Postgres DB
  oltb-db:
    image: postgres:15
    container_name: oltp_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/oltp_schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/db/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=oltp
      - POSTGRES_PASSWORD=oltp
      - POSTGRES_DB=oltp
    networks:
      - default
  #Superset
  superset:
    build: 
      context: ./docker/superset
      dockerfile: Dockerfile
    container_name: superset 
    ports: 
      - "8080:8088"
    environment:
    - SUPERSET_SECRET_KEY=AWhjVghhJKHvgF
    - ADMIN_USERNAME=admin
    - ADMIN_EMAIL=admin@superset.com
    - ADMIN_PASSWORD=admin
    networks:
      - default

    volumes:
      - ./docker/db/duckdb:/app/superset_home/db
  
networks:
  default:
    driver: bridge